### ISSUE TITLE
Getting a out of memory error...

### ISSUE THREAD

**Issue by fstltna** [minetest-tools/mapserver#39]
I have it set up but when starting it I get this:

```
INFO[0000] Starting mapserver                            version=3.0.0
INFO[0000] Loading default colors                        filename=/colors.txt prefix=colormapping size=704276 useLocal=false
INFO[0000] Loaded default colors                         count=16109
INFO[0000] Migrating database                            filename=mapserver.sqlite prefix=mapobjectdb.sqlite
INFO[0000] Migration completed                           elapsed=4.229358ms prefix=mapobjectdb.sqlite
INFO[0000] Starting http server                          port=8080 webdev=false
INFO[0000] Starting initial rendering job               
fatal error: runtime: out of memory
```

Any ideas?

**Comment by thomasrudin** [comment]
Strange, it should not consume that much memory...
Can you tell me something about your setup:
* Map-size
* Map-type (sqlite/postgres)
* RAM-Size
* Operating System

If it is possible could you provide a reproduction-world to test on?

Also: can you try to run in debug mode:
```
mapserver -debug
```

**Comment by fstltna** [comment]
Ok, I'm not sure of the map size, but I am using sqlite, RAM is 1GB, OS is Ubuntu 16.04. Attached is the debug output...
[mapserver_debug.txt](https://github.com/thomasrudin-mt/mapserver/files/3343516/mapserver_debug.txt)

**Comment by thomasrudin** [comment]
That may be related to:
https://github.com/thomasrudin-mt/mapserver/blob/master/doc/config.md#mapblockaccessormaxitems

Can you try setting the limits in the config file a bit lower:

**mapserver.json**
```
{
	"mapblockaccessor": {
		"expiretime": "5s",
		"purgetime": "10s",
		"maxitems": 100
	}
}
```

Those essentially control how many mapblocks are cached in-memory.
The default is 5000 mapblocks, a setting of 100 _should_ work but is slower during the initial rendering.

**Comment by thomasrudin** [comment]
no response, closing, feel free to reopen..
