### ISSUE TITLE
POI blocks

### ISSUE THREAD

**Issue by MilesBDyson** [minetest-tools/mapserver#45]
after placing a poi block and filling out the form, the icon did show up on the map after several minutes, digging the poi block to remove it the icon stayed, i could not see any way to remove it, after much searching for any documentation on how to use these nodes with no luck i tried placing the node again and resetting the form then removing the node and still the icon remains...   however after refreshing the web page the icon did get removed,  for some reason it seams the page was not updated correctly or automatically ... 

Minetest 5.1.0-dev
Firefox Web Browser

also wanted to mention that when setting up the server with the mapserver in active mode, i got a curl fetch error with code 0 every few seconds, i had to add the mapserver mod to the trusted mods list and restart the server to get the mapserver mod to work correctly, nothing of this is mentioned in any of the documentation for setting the mapserver up. :)

**Comment by thomasrudin** [comment]
> i had to add the mapserver mod to the trusted mods list and restart the server to get the mapserver mod to work correctly, nothing of this is mentioned in any of the documentation for setting the mapserver up. :)

See: https://github.com/minetest-tools/mapserver/blob/master/doc/mod.md#active-mode

> Enable http for the mapserver mod in your minetest.conf

**Comment by thomasrudin** [comment]
realtime-updates addressed here: https://github.com/minetest-tools/mapserver/issues/54
