### ISSUE TITLE
Include a sample NGINX configuration file

### ISSUE THREAD

**Issue by Elinvention** [minetest-tools/mapserver#60]
I think it would be useful to include a sample NGINX configuration file.

This is what I came up with:

```
upstream mapserver {
        server 127.0.0.1:8080;
}

server {
        listen 80;
        server_name example.org;
        return 301 https://example.org$request_uri;
}

server {
        listen 443 ssl;

        server_name example.org;

        include ssl.conf;

        location / {
                proxy_pass http://mapserver;
                proxy_http_version  1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
        }
}
```
However I'm not sure how to treat the websocket connection. It works but, I have to wait a while before I can see the websocket connection logged in the browser and the trains going around on the map.

**Comment by thomasrudin** [comment]
Sorry for the delay, i did not get notified about the issue... :confused: 

This works on the pandorabox-server:

https://github.com/pandorabox-io/pandorabox.io/blob/master/data/nginx/routes/map.conf
```
location /map/ {
	proxy_pass http://mapserver:8080/;
	proxy_buffering off;
	proxy_http_version 1.1;
	proxy_set_header Upgrade $http_upgrade;
	proxy_set_header Connection $http_connection;
	access_log off;
}
```

Along with this base-config:
https://github.com/pandorabox-io/pandorabox.io/blob/master/data/nginx/nginx.conf

The trains are updated with the POST from the minetest-server in the default 2 seconds interval:
https://github.com/minetest-tools/mapserver_mod/blob/master/init.lua#L4

Is the delay greater than the 2 seconds?
A solution would be for the mapserver to send the latest received json-data on the initial connection...

**Comment by Elinvention** [comment]
Thanks! Yes I left the interval at 2 seconds, but I definitely had to wait more before they appeared. I will try with that configuration and report back.

**Comment by Elinvention** [comment]
Nope it's still happening. I'm using the latest commit from master, Minetest 5.0.1, Firefox 69.0. I have to fiddle a bit with the map until trains appear on the map and keep updating every 2 seconds. Also before trains appear there is no websocket connection in Firefox's network graph. Then even if I press F5 it keeps working.

**Comment by thomasrudin** [comment]
Does the server have a public address and is the mapserver exposed?
I'd like to take a look at it myself, i can't reproduce that locally or on pandorabox :confused:

**Comment by thomasrudin** [comment]
stale, closing, feel free to reopen if the issue persists
